# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SmashingTV' do

end

target 'SmashingTVTests' do

end

target 'SmashingTVUITests' do

end

