# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

def import_pods
    pod 'Parse'
end

target 'SmashingTV' do
    import_pods
end

target 'SmashingTVTests' do
    import_pods
end

target 'SmashingTVUITests' do
    import_pods
end

